Fix indentation error

diff --git a/.github/workflows/cpp-linter.yml b/.github/workflows/cpp-linter.yml
--- a/.github/workflows/cpp-linter.yml
+++ b/.github/workflows/cpp-linter.yml
@@ -21,18 +21,18 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Run C++ Linter
-              id: linter
-              uses: cpp-linter/cpp-linter-action@v2
-              env:
-                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-              with:
-                style: 'file'
-                tidy-checks: ''
-                thread-comments: true
-                step-summary: true
+        id: linter
+        uses: cpp-linter/cpp-linter-action@v2
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          style: 'file'
+          tidy-checks: ''
+          thread-comments: true
+          step-summary: true
 
-            - name: Fail on Formatting or Tidy Errors
-              if: steps.linter.outputs.checks-failed > 0
-              run: |
-                echo "Linting failed! Please check the PR comments for specific issues."
-                exit 1
+      - name: Fail on Formatting or Tidy Errors
+        if: steps.linter.outputs.checks-failed > 0
+        run: |
+          echo "Linting failed! Please check the PR comments for specific issues."
+          exit 1
